compiler_opt/rl/gin_configs/ppo_nn_agent.gin
compiler_opt/rl/inlining_runner.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/train_locally.py

When we have unfinished tasks that we don't need to wait for, we risk entering into a timing issue where the rate of queueing more work is larger than the rate of clearing worker processes.
To both keep the system well-performing and robust to such corner cases, we track the unfinished work. We require the data collection plugin (e.g. inliner, regalloc) to have a timeout - so plugins are guaranteed to finish, once a worker acquires them. If a watermark of unfinished work is hit, we report and wait for it to drain (up to that watermark). If this happens frequently, the user should increase deadlines or check the corpus (maybe there are too many very large modules that take a long time to compile)
This design quite easily lends us the opportunity to use the data collected from work from …

Local training policy: ensure scheduled queue size is bounded

---

docs/demo/demo.md

With the recent transition to using gin to handle configuration so that adding more problem types is significantly more scalable (2ba448732b5c9aa9ed221ac70a0009293651701e), it seems like a couple things were overlooked in the inlining demo. The `compile_task` flag has been deprecated, but it was still present in the demo. There is also no mapping between `clang_path` and `llvm_size_path` and the actual config variables they need to alter (`runners.InliningRunner.*`). Finally, there is no flag providing the configuration implementation, which is needed according to the documentation in `compiler_opt/rl/problem_configuration.py`. This PR makes a couple quick fixes so that the demo functions as intended.

fix issues with gin bindings in demo

---

docs/demo/demo.md

Added some misc notes to the documentation regarding tensorflow versioning. When I tried getting my initial compile setup working, I'm highly confident that compiling with Tensorflow v2.8.0 caused the build to fail (Tensorflow v2.7.0 isn't compatible with Python 3.10 on Ubuntu 22.04, so I had to downgrade to 20.04), and then I ran into some linking issues when I tried building with a more recent version of libtensorflow to try and make things compatible. This seems to have been noticed in commit e11c886edd7e1e362fae6bbae4f2fca659b22fb3, and I'm going to try and do some more investigation into this issue to see if I can get the libtensorflow version upgraded. However, the buildbot script seems to be using v2.6.0 happily, so maybe there's just something specific with the configuration of …

Update demo to add in notes on depot_tools and tensorflow versioning

---

compiler_opt/rl/regalloc/regalloc_runner.py

Currently, when running `generate_default_trace.py` against the regalloc problem, it errors out when not using a ThinLTO corpus due to the expansion of the `file_paths` variable. This patch preserves functionality for the ThinLTO case while also allowing running `generate_default_trace` against the regalloc runner without using a ThinLTO corpus.

Modify regalloc runner to prevent needing a ThinLTO corpus for generating a default trace

---

compiler_opt/rl/regalloc/regalloc_runner.py

Adds an assert to make sure that the length of `file_paths` in `_compile_fn` in `regalloc_runner.py` is valid. Should theoretically be limited by the declaration of the parameters as a tuple, but this still allows for smaller values, which we also want to detect and throw an error before anything else happens.

Added assert to ensure length of file_paths is valid

---

compiler_opt/rl/regalloc/gin_configs/behavioral_cloning_nn_agent.gin

This patch adds the flag `regalloc.config.get_observation_processing_layer_creator.with_sqrt = False` to the regalloc behavioral cloning config. Without this flag explicitly being set to false, the models created by the behavioral cloning script for the regalloc model are not compatible with the local training script.

Fixed regalloc behavioral cloning

---

compiler_opt/rl/regalloc/gin_configs/behavioral_cloning_nn_agent.gin
compiler_opt/rl/regalloc/gin_configs/network.gin
compiler_opt/rl/regalloc/gin_configs/ppo_nn_agent.gin

This should help mitigate issues in the future like the one fixed in #27 as it refactors the gin configs for regalloc so that the common network parameters are stored in their own file and imported into the behavioral cloning and agent configs. Reducing code duplication and having a central place to make changes to the model should allow for easier changes and changes that are more likely to be correct. The same thing could probably also be done with the inlining config although with some differences due to the fact that there are many more configs (multiple common network configs need to be refactored out), and the standard behavioral cloning and agent configs use different network classes. Could be done with gin macros, but it doesn't refactor as nicely as the regalloc configs.

Refactored regalloc gin configs

---

compiler_opt/rl/inlining/__init__.py
compiler_opt/rl/problem_configuration.py
compiler_opt/rl/regalloc/__init__.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py

This simplifies support for compute distribution middleware where the
mechanism of distributing work is via class decorations. This also
simplifies handling gin bindings because the distribution code on our
end can fetch gin bindings before sending the work remotely.
(Issue #31)

[infra] Expose the runner class rather than a factory method.

---

compiler_opt/rl/data_reader.py
compiler_opt/rl/train_locally.py

Caching the results pre-shuffling prevents TF from recomputing the pre-shuffle batches from scratch repeatedly. 
A speedup of about >5x is expected for the input pipeline, and similarly for the training cycle times as well.

Add caching to input pipeline

---

compiler_opt/rl/inlining/__init__.py
compiler_opt/rl/inlining/config.py
compiler_opt/rl/problem_configuration.py
compiler_opt/rl/regalloc/__init__.py
compiler_opt/rl/regalloc/config.py
compiler_opt/tools/sparse_bucket_generator.py
docs/adding_features.md
docs/demo/demo.md

Currently, the vocab generator generates quantile buckets for all the different features regardless of whether or not they are relevant. This patch adds an option into the problem config so that features that don't require quantile buckets won't have them generated. This saves on some performance during vocab generation and prevents having to load a couple things during the preprocessing layer generation (although the latter difference is extremely insignificant). In addition to the config option, this patch also ties the config option into the vocab generator and both current problem configs. The major advantage of this feature is that it skips vocab generation for extremely large features (eg the new instruction based features for the regalloc model) that don't need vocab generated and …

Only generate/use vocab when needed

---

buildbot/buildbot_init.sh
check-license.sh

the only difference is that they don't need to check
encoding.

Extend license checking to .sh files

---

compiler_opt/distributed/__init__.py
compiler_opt/distributed/local/__init__.py
compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/distributed/local/local_worker_manager_test.py
compiler_opt/distributed/worker.py

This is meant as an in-place replacement of the current functionality,
but using a stateful worker object abstraction analogous to what Dask
supports. For local workloads, this implementation is faster than Dask's
LocalCluster (which may be due to misconfiguration). Because it's very
simple and introduces no new dependencies, even if LocalCluster
performance could be improved, the implementation would still be useful
for debugging.
The worker abstraction allows implementers specify a list of methods
that should be executed promptly on the server side, analogous to Dask's
`separate_thread=False` concept. For our purposes, we can use it to
implement full cancelation of work on the server side.
This patch introduces the worker manager, a subsequent patch will enable
its use in the rest of …

[infra] Introduce a simple local-process worker pool manager

---

compiler_opt/rl/inlining/gin_configs/ppo_nn_agent.gin
compiler_opt/rl/regalloc/gin_configs/ppo_nn_agent.gin
compiler_opt/rl/train_locally.py

This patch refactors the passed `num_modules` flag in `train_locally.py` into a setting in the gin configs while preserving the default value of 100. This is a parameter that can have a major impact on the performance of a trained model (at least with the regalloc case) and thus should probably be specified in the gin configs (when it deviates from the default value of 100) for the sake of reproducibility. 
Eg for the regalloc case, the result with `num_modules` set to 512 is a graph of the mean reward per iteration which displays the characteristic shape of a model that is training properly (only trained for 100k iterations):
And this is the same model trained for 600k iterations with `num_modules` set to 100:

Refactored train_eval to use num_modules from gin configs

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/compilation_runner_test.py
compiler_opt/rl/corpus.py
compiler_opt/rl/inlining/inlining_runner.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/regalloc/regalloc_runner.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py

Preliminary patch to refactoring file_paths tuple usage completely.
Allows distributed thinlto corpora to be optionally trained on independent of runner type
Prereq: #55 #56

Refactor file_paths tuple into ModuleSpec (preliminary)

---

.github/workflows/main.yml
dev-requirements.txt

Since we are now using yapf to format the repository, it makes sense to
have yapf in the development requirements. This commit also adds a yapf
format check to the CI to ensure that all new code changes are properly
formatted.

Add yapf to CI and dev dependencies

---

Dockerfile

@petrhosek Here are the base dependencies for `ml-compiler-opt` based on the buildbot dependencies. I'm assuming you're just using all of these dependencies for building LLVM/clang? This is what I guess would be considered the "official" dependency setup for LLVM, but depending upon what you need, I can change it up. Just let me know.

Added dockerfile with base dependencies

---

compiler_opt/tools/extract_ir.py
compiler_opt/tools/extract_ir_test.py

New flag: `is_lld_thinlto` will auto-find the files generated from lld and copy them over

Add support for extracting lld-thinlto corpora

---

compiler_opt/rl/trainer.py
compiler_opt/rl/trainer_test.py

Currently, all of the tensorboard variables get updated every
single iteration. This is quite costly in terms of performance. I'm
seeing about a 25% performance improvement by just running this once
every 100 iterations instead of running it every iteration. The data
showing up in tensorboard will definitely be more sparse, but when
running everything locally, it seems to all appear just fine, and I'm not sure
getting data down to the iteration level is quite necessary, especially
given the large performance penalty.
I implemented this as an optional flag that can be passed from the command
line with what I believe is a reasonable default (once every 100 iterations), 
so it can be easily adjusted by the user if necessary while also being
a completely reasonable default for good …

Make the tensorboard data interval adjustable

---

compiler_opt/rl/constant.py
compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py
compiler_opt/tools/extract_ir.py
compiler_opt/tools/generate_default_trace.py
compiler_opt/tools/generate_default_trace_test.py

- This adds 'global_command_override' functionality for lld-thinlto corpora, exposed in metadata.json
- Setting the above in the corpus_description.json file will default the runners to using that as the base command, rather than looking for a .cmd file

Replace module_paths with corpus_description.json

---

compiler_opt/rl/agent_creators.py
compiler_opt/rl/policy_saver.py
compiler_opt/rl/train_bc.py
compiler_opt/rl/train_locally.py
compiler_opt/rl/trainer.py

This clarifies we use TFAgents rather than raw saved models, and helps with readability and discoverability (the latter in an IDE in particular)

Type APIs working with policies

---

check-license.sh
compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py
compiler_opt/rl/data_reader.py
compiler_opt/tools/extract_ir.py
compiler_opt/tools/extract_ir_test.py
compiler_opt/tools/generate_default_trace_test.py

- ensure the '-cc1' flag exists for commands extracted from .cmd files, as it is required
- disabled yapf formatting on data_reader's dataset builder
- gracefully handle when a compile_command doesn't have the -o option
- check-license.sh now ignores shebang lines

Minor fixes

---

compiler_opt/rl/trainer.py
compiler_opt/rl/trainer_test.py

- Decouples the summary intervals, so one is not reliant on the other
- Switches to modulo instead of remembering the last step number- this is more robust/less-error-prone, especially if training is restarted at some non-zero step N (which previously caused no scalar data to be written, at least for the first N + interval steps)

Fix metric logging

---

docs/demo/demo.md

This pull requests corrects the libtensorflow version needed for the demo. Based on https://github.com/google/ml-compiler-opt/issues/71

corrected libtensorflow dependency for demo

---

buildbot/build_tflite.sh

This script builds TFLite together with all its dependencies and
generates a CMake cache file that can be used from other projects.

Script to build TFLite and its dependencies

---

experimental/docker/README.md
experimental/docker/development.Dockerfile

Development mode dockerfile and instructions on use in a `README.md` inside a newly created `docker/` directory. Should be something useful for anyone working on the project who is struggling with creating a working build environment and also general development workflows that use docker.

Add development mode dockerfile and info on use

---

compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/rl/local_data_collector_test.py

If process was killed while its output queue is accessed, the queue would be left broken, causing msg_pump to not die, and .join() to never unblock.
Also, fix a misc. indentation bug on a test case

Fix worker shutdown

---

compiler_opt/distributed/local/local_worker_manager_test.py
compiler_opt/rl/local_data_collector_test.py

Local-scoped classes won't be pickle-able following an internal change.

Promote locals in tests to module scope

---

compiler_opt/rl/inlining/gin_configs/ppo_nn_agent.gin
compiler_opt/rl/problem_configuration.py
compiler_opt/rl/regalloc/gin_configs/ppo_nn_agent.gin
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py
compiler_opt/tools/generate_default_trace_test.py

options from gin_configs
Currently there are two places where we are specifying
deletions/additional flags when processing commands for building object
files, in ppo_nn_agent.gin for both the inlining and regalloc case. This
patch refactors generate_default_trace.py into two separate files so
that the actual function that handles the tracing can be configured in a
gin file. There are new gin files for the regalloc and inliner case that
specify options specifically for the default trace. This makes
maintenance easier as if these flag options need to change, they only
have to be changed in one place (per optimization case). This also makes
it possible to still warmstart models easily if the flags between the
two cases diverge, and it makes it possible to specify other options for
the …

Refactor generate_default_trace to accept build command CLI modification

---

compiler_opt/rl/local_data_collector.py
compiler_opt/rl/train_locally.py

Minor cosmetic changes

---

compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py

- Rather than pass around a list of module_specs, pass around a Corpus object instead
- Corpus has built in filter and sample method
- sample will sort by size descending, with the goal of optimizing compile order for time

Add Corpus abstraction & sorting w/ size

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/compilation_runner_test.py
compiler_opt/rl/inlining/inlining_runner.py
compiler_opt/rl/regalloc/regalloc_runner.py

Replace _compile_fn with compile_fn

---

compiler_opt/distributed/local/local_worker_manager.py

- acquire lock -> future.set_result -> done_callback() -> ... -> _Stub. __getattr__ -> remote_call -> fetch lock -> deadlocked
- Releasing the lock earlier resolves this.

Resolve potential deadlock in local_worker_manager

---

compiler_opt/rl/constant_value_network.py
pytest.ini
requirements.txt

We need to get past TF 2.9, but 2.10 isn't released yet, and there are
compat issues between 2.10-RC1 and tfagents. The recommended approach is
to install nightlies of these.

Prepare requirements for tflite

---

requirements.txt

Currently, some of the dependencies that get pulled in by the tensorflow nightly packages pull in the current nightly version rather than the nightly version that is currently set in `requirements.txt`. This PR pins all of these dependencies to the correct versions, removes some of the older dependencies that need to be replaced by a nightly version, and bumps some other tensorflow related packages.

Pin all tensorflow nightly dependencies

---

.github/workflows/main.yml
pytest.ini
requirements.txt

This PR changes the Github CI to test against Python 3.9 and 3.10 instead of 3.8 and 3.9. Could be adjusted if we still want to support 3.8 though. Also adjusts the versions of some dependencies so that they are compatible with 3.10. There are a couple new deprecation warnings internal to tensorflow that I've excluded in the `pytest.ini`. Nothing super major and I'm guessing it will get fixed by the time anything gets even close to being deprecated.

Migrate to Python 3.10

---

compiler_opt/rl/policy_saver.py
compiler_opt/rl/policy_saver_test.py

Currently just saving it next to the saved model, so we can start
iterating using tflite models with llvm. Eventually we can get more
efficient.

TFLite: when saving a saved model, also save the tflite model

---

compiler_opt/rl/compilation_runner.py

Expose compilation timeout programatically

---

compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py

Modify Corpus to store module specs as a tuple

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/compilation_runner_test.py
compiler_opt/rl/inlining/inlining_runner.py
compiler_opt/rl/regalloc/regalloc_runner.py

Default to using self.cancellation_manager

---

experimental/chromium-bitcode-embedding.patch

This PR adds the chromium patch that was worked on in [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/3731216) that we have decided to maintain downstream. I've put it in the `./experimenal` directory currently. Let me know if it would be better off somewhere else.

Add chromium patch

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/compilation_runner_test.py
compiler_opt/rl/data_collector.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/policy_saver.py
compiler_opt/rl/policy_saver_test.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py
compiler_opt/tools/generate_default_trace_test.py

This sets up the trainer to work with potentially remote workers by passing a serialized object to them. Each worker, then, serializes the policy locally, after which data collection continues as usual.
The main inefficiency is that we save the policy per request handler, and even if the training is local. Policies are small objects, however (at least currently), so this shouldn't be cause of concern. Upon measuring this for 100 and then 500 modules, with 128 workers:
- 100 modules: ~7% regression in the compile time component of training
- 500 modules: ~9% improvement
At this point, I'd take neither regression nor improvement as meaningful, and since, additionally, compilation time is about 1/10 of overall time, the complexity tradeoff of a design optimizing for the local case is …

Pass serialized policies to workers

---

compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py

Using 'delete' and 'add' for flags that must actually be present - such as -fthinlto-index, or, later, profiles - is a bug farm. This patch explicitly models such flags as something that cannot be 'deleted' or 'added', and must be somehow converted (contextualized to the location of the files(presumably) used as values of those flags). The conversion rule is a formatting string which uses a 'context' value, which will have fields populate at the time of the conversion.
Some tests had to have the order of some flags adjusted a bit as a NFC side-effect.
This closes issue #85

Explicitly model 'replace' flags

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/compilation_runner_test.py
compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py
compiler_opt/rl/inlining/inlining_runner.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/regalloc/regalloc_runner.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py
compiler_opt/tools/generate_default_trace_test.py

This change removes the assumption that the corpus is co-located with the workers. The new design relies on the assumption that the workers are reachable via a high-throughput network (datacenter setup). The trainer prefetches the modules for the next iteration and sends them as data blobs to the workers.
The rest of the change trickles out from this:
- the corpus operates internally with a metadata object about modules, `CorpusElement`
- workers are given a `LoadedModuleSpec` which contains the data of the module (and its thinlto index, if needed).
- command line final shape is done on the worker side
This had the side-effect that responsibilities could be reassigned as follows:
- the corpus constructor handles preparing the `CorpusElement`s, with all the necessary flag modification …

Make the corpus remote wrt workers

---

docs/demo/demo.md

We refactored this flag a while ago to be specified in the gin config for the relevant problem to improve reproducibility, especially in the regalloc case, but I forgot to remove the flag from the demo. This patch removes the flag from the demo, making everything (hopefully) plug and play.

Removed num_modules flag from RL training in demo

---

compiler_opt/benchmark/benchmark_chromium.py
compiler_opt/benchmark/benchmark_llvm_test_suite.py
compiler_opt/benchmark/benchmarking_utils.py

Should help with the other half of #129. The benchmarking code currently sets the TENSORFLOW_C_LIB_PATH CMake variable when building LLVM. However, this doesn't make sense going forward as we have shifted mostly everything over to TFLite and we don't need to have MLGO development mode enabled for benchmarking in either case. This patch explicitly removes the flag so that the benchmarks simply build LLVM in MLGO release mode.

Removed tensorflow_c_lib_path flag from LLVM build for benchmarking

---

compiler_opt/rl/train_locally.py

This allows reusing `train_locally` with other worker managers. It's the minimum refactoring necessary - subsequent ones would make this a library and also remove the `_local` suffix from this and a few other places, since they aren't "local" in any sense anymore.

Make the worker manager type a parameter to `train_eval`

---

Dockerfile

The current base image, Ubuntu 22.04LTS has a much newer kernel and glibc. Fuchsia infra builders is running into issues to support it. This patch changes the base image to debian bullseye which aligns with what infra builders use.
This change will drops the python revision from 3.10 to 3.9.

Update the Dockerfiles to use a base image supported by Fuchsia infra.

---

compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/distributed/local/local_worker_manager_test.py
compiler_opt/distributed/worker.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/train_locally.py

The motivation is:
- allowing worker managers specify the level of concurrency for a worker. This is set to '10' right now by the data collector, but it's really specific to the worker set up. For the local case, where we max out the hardware threads with workers, 10 is overly-generous. For a distributed case, a number approaching the hardware threads would be more appropriate
- allowing distributed worker managers update the set of available workers over time. Workers could get preempted, or new ones become available. Having a way to periodically check and update what's available - albeit there are never guarantees a worker, once discovered, stays alive - helps avoid artificial starvation.
The rest is renames that fall out of this refactoring.

Have the worker pool context produce a pool object

---

experimental/chromium-thinlto-corpus-extraction.patch

Should be working in upstream Chromium once [this](https://chromium-review.googlesource.com/c/chromium/src/+/3941232) CL gets merged as that toolchain roll will grab [my commit](https://github.com/llvm/llvm-project/commit/f741815ddb49e3ed26de327a51ccf60f66f21d46) that fixes some issues related to thin archives in these builds.

Added patch for extracting corpora from Chromium with ThinLTO

---

compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/distributed/worker.py

If the local worker manager's processes aren't forked (which depends on what the default for `multiprocessing.get_context` is) the gin bindings won't be available. So we just pass them explicitly.

Explicitly pass the worker's gin config

---

compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py
compiler_opt/tools/generate_default_trace.py

That makes it easier to filter arbitrary modules (e.g. from an allow/deny list)

Corpus: let module_filter be a function

---

compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py

It's possible the original command line has brackets that otherwise python string formatting will interpret as part of the worker contextualization formatting (i.e. LoadedModuleSpec.build_command_line). We need to escape such brackets upfront when loading the command line.

Escape '{' '}' brackets in original command line

---

Dockerfile

This gives more precise control over the Python version.

Use the official Python image as base image

---

.github/workflows/main.yml

CI currently is giving a lot of deprecation warnings of the form:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Due to using an old version of the `setup-python` action. This PR bumps the `setup-python` version to v4 so that the action doesn't use the deprecated path anymore, thus getting rid of the deprecation warning.

Bumped setup-python version to fix Github CI deprecation warnings

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/data_collector.py
compiler_opt/rl/local_data_collector.py
compiler_opt/rl/local_data_collector_test.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py
compiler_opt/tools/generate_default_trace_test.py

The model_id parameter allows joining compilation results with the model used during the compilation. This is useful for debugging errors in training as well as for ensuring experience freshness in the distributed training setting.

Add a model_id parameter to collect_data.

---

compiler_opt/tools/extract_ir.py

ThinTLO corpus extraction in extract_ir.py is designed to be used without an input file (ie an lld params file or a
compile_commands.json). However, if the user passes in an input while trying to do local thinLTO corpus extraction the extraction might partially succeed, or even fully succeed without giving any indication of what might be amiss. This patch makes these configurations error out to reduce confusion.
Follow up patch to conversation on Slack with Mircea about this issue.

Fail fast in IR extraction if using local thinLTO and an input

---

README.md
docs/adding_features.md
docs/contributing.md

Should fix #181.
Fixes the demo links that originally pointed to the inlining-for-size demo to the new path for that demo and adds a link to the regalloc demo in the README.

Fixed demo links

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/constant.py
compiler_opt/rl/constant_value_network.py
compiler_opt/rl/data_reader.py
compiler_opt/rl/data_reader_test.py
compiler_opt/rl/feature_ops.py
compiler_opt/rl/feature_ops_test.py

Distributed training has slightly different requirements than our current setup. This commit includes some small changes to prepare for the distributed training commit.
Relevant changes:
- add ability to observe compilation results within each worker (this will be used to efficiently send experiences to reverb). This is intended for users who need to observe compilations while they are in the distributed worker pool, rather than after they have been coalesced in the collection script.
- add a sequence example dataset creator which doesn't batch examples (reverb does not handle batched examples).
- slightly change the parsing logic to handle distributed PPO evaluation and training. In particular, distributed training requires that compute_value_and_advantage_in_train=False, which changes …

Prepare for distributed training infrastructure.

---

compiler_opt/rl/corpus_test.py

Previous, test_braces_in_cmd used a fixed tempdir 'some/temp/dir' which would break the test in some environments. This changes the test to use a directory created from self.create_tempdir(), following the convention of other tests in the file.

Use create_tempdir in corpus_test.py.

---

compiler_opt/rl/agent_creators.py
compiler_opt/rl/distributed/__init__.py
compiler_opt/rl/distributed/agent.py
compiler_opt/rl/distributed/gin_configs/regalloc/common.gin
compiler_opt/rl/distributed/gin_configs/regalloc/ppo_collect.gin
compiler_opt/rl/distributed/gin_configs/regalloc/ppo_eval.gin
compiler_opt/rl/distributed/gin_configs/regalloc/ppo_reverb.gin
compiler_opt/rl/distributed/gin_configs/regalloc/ppo_train.gin
compiler_opt/rl/distributed/learner.py
compiler_opt/rl/distributed/ppo_collect.py
compiler_opt/rl/distributed/ppo_collect_lib.py
compiler_opt/rl/distributed/ppo_eval.py
compiler_opt/rl/distributed/ppo_eval_lib.py
compiler_opt/rl/distributed/ppo_reverb_server.py
compiler_opt/rl/distributed/ppo_reverb_server_lib.py
compiler_opt/rl/distributed/ppo_train.py
compiler_opt/rl/distributed/ppo_train_lib.py
requirements.txt

Distributed training works via four processes:
- ppo_reverb_server.py
- ppo_train.py
- ppo_collect.py
- ppo_eval.py
ppo_train, ppo_collect, and ppo_eval communicate via ppo_reverb_server. The reverb server has two tables of data: one that holds the most recent model weights, and another that holds training data. The train script fetchs examples from reverb, trains, then uploads new model weights to reverb. The collect script fetches the latest model weights, collects training data, then uploads it to reverb. The eval script fetches the latest model weights and writes evaluation data to tensorboard.
Training is distributed, so each of these processes can live on different servers, and you can have as many collect and eval jobs as you need.
Distributed accelerator training is done via …

Add distributed PPO training.

---

Pipfile.lock
buildbot/buildbot_init.sh

Regenerated the lockfile with Python 3.8 (and ignored some changes in nightly package version numbers) to add in compatibility with Python 3.8 and 3.9 since those versions don't have `importlib-metadata` in the Python standard library like Python 3.10 does.
Also removes the stopgap introduced in cd87863dea0c0f619721794eb5566978ffda0860.
Should close #192.
Tested locally *since the CI is just running duplicate jobs against Python 3.10 for some reason) against all three python versions that we're supporting (3.8, 3.9, and 3.10), and all tests are passing.

Regenerated lockfile with Python3.8 to increase compatibility

---

.github/workflows/main.yml

My commit to move everything to pipenv also updated the CI to use
pipenv, but pipenv is picking up the wrong Python version when creating
the virtual environment, so all of the jobs are using Python 3.10. This
patch fixes that behavior by having pipenv install the packages to the
system rather than creating a virtual environment.
Work in progress since #193 needs to get merged first so that the CI passes on this.
Currently rebased this branch on top of that branch in my fork so that the commit
is included here.
Should also version-dependent bugs like #192 from getting through CI for the time being again.

Fix python version ci

---

experimental/docker/development.Dockerfile

This updates the development mode Dockerfile to use `pipenv` for dependency management and also makes sure to clear the cache to save a little bit of storage space.

Update development mode Dockerfile to work with pipenv

---

docs/inlining-demo/demo.md

We use -C ${TFLITE_PATH}/tflite.cmake instead of TENSORFLOW_C_LIB_PATH these days.

Update the doc regarding TENSORFLOW_C_LIB_PATH

---

Dockerfile

This updates the `Dockerfile` to use `pipenv` after #189. Also clears the `pipenv` cache (which also clears the pip cache) afterwards since it's a waste couple hundred MB.
Pinging other people on the Fuchsia team who have made changes here before that Github won't let me add as reviewers for some reason:
@faizan-m @zeroomega

Update Dockerfile to use pipenv

---

compiler_opt/rl/data_reader_test.py

Make the data source a parameter. Also remove `_agent_name` from the test state, it's really something specific to each state (and, thus, not needed as a field)

Further parameterize data_reader_test

---

buildbot/build_tflite.sh

Now that the transition to the new dependency free logger is complete, there's no longer a need to have a protobuf build in order to build LLVM in MLGO development mode. This patch removes the protobuf build from build_tflite.sh which will remove the extra protobuf build from both the buildbots and the development mode Docker image.

Remove protobuf build from build_tflite.sh script

---

compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/distributed/local/local_worker_manager_test.py

Positional arguments for worker_class wouldn't work at all when creating a local worker pool, which surprisingly didn't cause any issues previously because we only ever instantiated the pool with kwargs for the worker_class. This is because of how the function signatures for _run and _run_impl were written in local_worker_manager.py. The modified test in this commit would previously fail without the changes in local_worker_manager.py.

Fix bug with positional arguments in the LocalWorkerPool.

---

compiler_opt/distributed/local/local_worker_manager.py

These functions are helpful to creating local worker managers where context managers are not appropriate.

Refactor LocalWorkerManager to call out to helper functions.

---

experimental/chromium-bitcode-embedding.patch
experimental/chromium-thinlto-corpus-extraction.patch

There have been some changes within the Chromium build system that have broken these patches, making work on Chromium with MLGO (especially through the demo) more difficult than it needs to be.
This patch rebases these patches so they apply cleanly (when performed in order) against a current (as of this commit) checkout of the Chromium source code.

Rebase Chromium Patches

---

compiler_opt/tools/sparse_bucket_generator.py

Previous implementation was broken as using transpose assumes that `data_list` is a 2D array.
However, in certain cases (when all the feature values array lengths are the same) the `data_list` can be a 3D array as the call to `data_list = np.array(list(dataset.as_numpy_iterator()), dtype=object)`  merges inner np arrays and converts `data_list` into one big 3D array.

Fixes the swap of data and feature dimension to work in the general case.

---

compiler_opt/distributed/buffered_scheduler.py
compiler_opt/distributed/buffered_scheduler_test.py
compiler_opt/rl/local_data_collector.py

The user can just specify how to call a worker with some work, instead of having to go through the trouble of creating a work factory and so on.

Simplify scheduling work on a worker pool

---

compiler_opt/distributed/buffered_scheduler.py
compiler_opt/distributed/buffered_scheduler_test.py
compiler_opt/rl/local_data_collector.py

They return canonical futures (i.e. `concurrent.futures.Future`). This is great because we can then use any `Future` APIs, e.g. `concurrent.futures.wait`.

Change the return type of buffered_scheduler APIs

---

compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/distributed/worker.py
compiler_opt/distributed/worker_test.py

We can just accept `**kwargs` - this allows usage like
`worker.get_full_worker_args(some_type, arg1=val1, arg2=val2)`

Make `worker.get_full_worker_args` more user friendly

---

compiler_opt/tools/extract_ir.py

Needs to be marked before `app.run` is executed.

Fix output_dir requirement setting

---

compiler_opt/rl/train_locally.py

Write reward_stat_map to separate file and atomically rename to avoid data corruption when backing up an instance/snapshots while a new version of the file is written.

Write reward_stat_map atomically

---

compiler_opt/rl/compilation_runner.py
compiler_opt/rl/data_collector.py

This also removes the currently unused `compilation_timeout` parameter from the CompilationRunner constructor to avoid discrepancies.

Ensure data_collector.DEADLINE_IN_SECONDS is higher than compilation_runner.COMPILATION_TIMEOUT

---

compiler_opt/tools/extract_ir_test.py

Otherwise the test won't run from the command line.

Setting `output_dir` for extract_ir_test

---

compiler_opt/es/gradient_ascent_optimization_algorithms.py
compiler_opt/es/gradient_ascent_optimization_algorithms_test.py

This is part of the effort to port the work by Krzysztof Choromanski, Mark Rowland, Vikas Sindhwani, Richard E. Turner, Adrian Weller:  "Structured Evolution with Compact Architectures for Scalable Policy Optimization", https://arxiv.org/abs/1804.02395
First step in Issue #248

Add gradient ascent optimization algorithms

---

.github/workflows/main.yml

The last patch removed the remaining requirements.txt as it was leftover from the pipenv transition. However, this broke the CI as setup-python's cache is set to pip which depends upon the hash of a requirements.txt. This implements a quick fix by setting the cache dependency path (used for the hash) to the Pipfile.lock. This is not optimal since the pipenv deps don't get cached (based on my testing), but they weren't before either (as far as I can tell). More testing is needed, but this should get the CI green.

Quick CI Fix

---

.github/workflows/main.yml

This fixes the caching for python dependencies in the CI by making pipenv install in a virtual environment and telling the setup-python action to cache this venv as it doesn't currently support the global pipenv cache. This increases the speed of some of the fast jobs (like the yapf format checker) quite a bit. Formatting went from about 2.5min to about 0.7min in my testing. This assumes that the cache is warm.

Fix caching in CI

---

compiler_opt/tools/extract_ir.py

For whatever reason, the section names for .llvmcmd and .llvmbc are different on macos. One problem is that macos uses macho object files instead of elf, so in addition to the section names there are segment names that need to be specified. The other problem is that regardless of the segments, the section names are different. This patch makes the segment name configurable by a flag, and gives sensible defaults for linux + documentation for macos.

Fix extract_ir.py for macos.

---

compiler_opt/rl/corpus.py
compiler_opt/rl/corpus_test.py
compiler_opt/rl/local_data_collector_test.py

This is useful for supervised learning contexts where we want to train in fixed epochs, where in each epoch we visit each module in the corpus exactly once.

Add SamplerWithoutReplacement to corpus.py.

---

.gitignore
pyproject.toml

Adds a basic `pyproject.toml` so that we can package the ML python tooling for use outside of the repository.

Add pyproject.toml to enable packaging

---

compiler_opt/tools/extract_ir.py
compiler_opt/tools/extract_ir_lib.py
compiler_opt/tools/extract_ir_test.py

This commit refactors most of the functional elements of extract_ir.py into a library. This serves a couple of purposes. It makes some elements of the code base a little bit cleaner (no more hacky flag tricks with absl to get things working in unit tests) and can be seen as making some things slightly more readable. In addition to this, it enables use of these functions in other areas, particularly downstream projects within the compiler_opt python package.

Refactor functionality of extract_ir.py into a library

---

compiler_opt/tools/combine_training_corpus.py
compiler_opt/tools/combine_training_corpus_lib.py
compiler_opt/tools/combine_training_corpus_test.py

This patch refactors combine_training_corpus.py into a library file that can easily be imported in downstream projects (and other utilities). This also makes unit testing slightly easier (as no special accomodations have to be made for CLI flags). This patch adds in two unittests for combining training corpora as well.

Refactor combine_training_corpus.py into script and library

---

compiler_opt/tools/extract_ir.py
compiler_opt/tools/extract_ir_lib.py
compiler_opt/tools/extract_ir_test.py

This patch adds in a directory input to extract_ir.py where the script does a glob for *.o files inside the specified directory. This is useful in cases where it is easy to specify specific flags through a build system (like the necessary -Xclang -fembed-bitcode=all), but the build system produces no manifest of compilation commands like CMake's compile_commands.json. This isn't reccomended to use in place of a proper manifest but is necessary for supporting build systems like Make.

Add directory input to extract_ir.py

---

.github/workflows/packaging.yml
compiler_opt/package_config.py
pyproject.toml

This commits adds in infrastructure to push package builds to Pypi nightly and on command. This all changes the versioning of the python package from a single fixed value to a dynamically generated value that includes the current date/time.
This shouldn't introduce too much maintenance burden on other maintainers as it is relatively self-maintained within the repository. 
I would've preferred to not have to introduce a new `package_config.py`, but adding a `__version__` attribute to `__init__.py` causes setuptools to complain about `absl` not being present as it isn't included in the build environment and placing the Python file somewhere else causes build failures as it doesn't get included in the final package.
I would like to add packaging dependencies to the `Pipfile`, but currently …

Add packaging CI

---

compiler_opt/tools/extract_ir_lib.py

My refactoring earlier in 32064da4250c37850f376663eff1cf1b79ab228a ended up breaking the extract_ir.py script as local objects can't be pickled. This patch changes everything back to using a functools.partial() but maintains the spirit of the original refactoring by still eliminating the global helper function.
I would like to add in a test case for this but it would have to be an integration style test to get the setup correct and we don't have the infrastructure to do that currently.

Fix run_extraction after earlier patch

---

compiler_opt/tools/make_corpus.py
compiler_opt/tools/make_corpus_lib.py
compiler_opt/tools/make_corpus_test.py

This patch adds in the ability to extract raw bitcode from a directory. This is motivated primarily by extracting LLVM IR bitcode from rust projects as it is quite easy to emit LLVM bitcode for each target but bitcode embedded in object files is much less trivial and neither solution currently provides command line arguments so they need to be reconstructed regardless.
This could probably benefit from some refactoring in the future to make it more clean. I held off on any additional refactoring before this patch as some of it was less trivial and I need some feedback at how specific IR extraction techniques are used. I believe we could unify the `--thinlto_build` and `--input_type` flags (assuming that distributed ThinLTO is always done with a linker parameter file which I'm unsure of) …

Add ability to extract raw bitcode

---

compiler_opt/rl/distributed/ppo_collect_lib.py
compiler_opt/rl/distributed/ppo_eval_lib.py
compiler_opt/rl/train_locally.py

This was post PR #237, unfortunately pytype doesn't detect these types of errors, and we don't have unit tests for these paths.

Fix spurious AgentConfig member reference

---

compiler_opt/tools/extract_ir.py
compiler_opt/tools/extract_ir_lib.py

This commit adds a logging verbosity level flag to extract_ir.py and the appropriate plumbing/implementation in extract_ir_lib.py. This is primarily motivated by these errors coming up quite often in non-trivial builds (as it is fairly often there is some assembly or some flags don't get passed around somewhere) and not providing a very high signal to noise ratio, especially when used as a library against a bunch of projects at once.
I've implemented this as a custom flag rather than using absl's `logging.get_verbosity` and `logging.set_verbosity` as I think this approach is a bit more expressive for the purposes here, and it also avoids us needing to set global state which is nice within the project and especially for downstream users (although it's not a big switch to do so the other …

Add logging verbosity level flag to extract_ir.py

---

compiler_opt/tools/make_corpus.py

Currently, the warning message is specified using logging.warn rather than logging.warning and the former is deprecated. This patch also adds appropriate spacing and fixes spelling to make the message appear as intended.

Fix make_corpus warning message

---

compiler_opt/tools/make_corpus_lib.py
compiler_opt/tools/make_corpus_test.py

Currently the functions in make_corpus_lib assume they are working with a full file path whereas the tooling in extract_ir truncates the .bc/.cmd extensions and only has the object file. This discrepancy means that tooling that works with downstream products of corpora from extract_ir doesn't work without modification with corpora from make_corpus (ignoring the missing .cmd files). This patch makes make_corpus match the behavior of extract_ir.

Make make_corpus functions consistent with extract_ir functions

---

compiler_opt/tools/combine_training_corpus.py

My last patch to the file refactoring it into a separate library inadvertantly broke the actual script as I removed the indentation from the statement calling into the library. This means the library never actually gets called with the correct arguments and it doesn't end up working properly.

Fix combine_training_corpus.py

---

compiler_opt/tools/combine_training_corpus_lib.py
compiler_opt/tools/combine_training_corpus_test.py

Currently the combine corpus tooling just looks through all files and folders in a directory, assuming them all to be folders with a corpus_description.json in them. We don't actually throw an error (only logging one), but it makes sense to be more robust and not log an error when we do something like iterate over a logging file. This patch also removes the tensorflow file code from this library which provides a couple benefits. It means we no longer have to load tensorflow to call the tool which is a significant time-savings and developer tooling like pylint works better on the standard library functions.

Make combine_corpus only look at folders with a corpus description

---

buildbot/build_tflite.sh
buildbot/buildbot_init.sh

Reverts google/ml-compiler-opt#293
Hit commit too soon, the dependencies in tensorflow haven't actually landed yet.

Revert "Bump TFLite commit"

---

buildbot/build_tflite.sh
buildbot/buildbot_init.sh

This patch relands 49e5d321db15255d297d6691b90197e21dfaabd6, bumping the TFLite version after that commit was mistakenly landed without waiting for some upstream patches in Tensorflow land first.
Fixes #292
Dependent on https://github.com/tensorflow/tensorflow/pull/61768 and https://github.com/tensorflow/tensorflow/pull/61767

Reland "Bump TFLite commit (#293)"

---

compiler_opt/tools/extract_ir_lib.py
compiler_opt/tools/extract_ir_test.py

Add support for `arguments`-style compilation databases (#297)

---

compiler_opt/rl/log_reader.py
compiler_opt/rl/policy_saver.py
compiler_opt/type_map.py

We have 3 scalar type representations: tensorflow, ctypes, and string names. Not unlikely we may get a fourth, numpy. This patch factors out all the associations into a central place. Modules can build their own maps as needed from it (i.e. name->ctype or dtype->name, etc)

Unify scalar type associations

---

compiler_opt/distributed/local/local_worker_manager.py

It turns out tflite conversion uses under the hood numexpr. Numexpr spawns a bunch of threads at module init. So if the main process converts a model, then forks and the resulting processes try converting a model, too, the state the forked processes work on appears like having been initialized. They hang waiting for results.
Using `spawn` and not `forkserver` because the latter still runs this risk. Spawning may be slower, but in the grand schema of things (training time), slightly larger init time is not that problematic.

[local-worker-mgr] Force using 'spawn' for process creation

---

compiler_opt/rl/compilation_runner.py

This flag doesn't do anything in the compiler at this point and is completely redundant. Remove it because of this and to avoid confusing future readers of the code.

Remove tfutils-use-simplelogger flag

---

buildbot/buildbot_init.sh

This patch installs the development dependencies on the buildbot in addition to the normal python dependencies so that we have pytype available. This is necessary for running the pytype tests recently added on the LLVM side so we can prevent regressions while waiting for precommit CI to be implemented on the LLVM side.

Install pytype on buildbot

---

docs/regalloc-demo/demo.md

Fixes a leftover from https://github.com/google/ml-compiler-opt/commit/7a62027deb1ee226e5bd243140b47dc21fcec854

docs: regalloc-demo: Fix a typo in corpus extraction command

---

docs/inlining-demo/demo.md

This patch removes the compile_task flag from the evaluation documentation for the inliner demo. This flag was removed in 2ba448732b5c9aa9ed221ac70a0009293651701e and the documentation was never updated.
Fixes #340.

Misc improvements to inlining evaluation docs in demo

---

compiler_opt/es/blackbox_learner_test.py
compiler_opt/es/policy_utils_test.py
compiler_opt/rl/inlining/config.py
compiler_opt/rl/trainer_test.py

The compiler side change will follow, but training can continue with this repository at HEAD because LLVM will patch features it can't find by allocating appropriate buffers and just never passing them to a model.

Remove `inlining_default` as it's not used by anything

---

buildbot/build_tflite.sh
buildbot/buildbot_init.sh

This patch bumps the TFLite version (along with versions of dependencies) so that we can get rid of the pthreadpool dependency.

Bump TFLite Version

---

compiler_opt/es/blackbox_optimizers.py

https://github.com/scipy/scipy/blob/87c46641a8b3b5b47b81de44c07b840468f7ebe7/scipy/optimize/_linesearch.py#L29

Handle scipy 1.12 breaking change post v 1.12

---

compiler_opt/es/blackbox_optimizers.py

This patch replaces instances of np.Inf with np.inf, which is needed for numpy 2 compatibility.

Fix np.Inf for numpy 2

---

README.md

This patch updates the README to better showcase the package installation commands. Most people probably just want to install everything and it probably won't hurt if they do so. So make that the default and then add a clarifying explanation and what is what rather than telling them to install more packages below.

Better showcase package installation command

---

.github/workflows/main.yml

This patch makes two primary changes to the CI config. It restricts the CI running on push events to only run on the main branch. This prevents the CI from running twice on PRs from branches in the main repository, which are needed for stacked PRs.
Additionally, this PR sets the permissions at the top of the file, which is a general best practice for Github workflows for security reasons.
Additionally, bump a couple of the actions that were using deprecated NodeJS versions so we do not get the warning anymore.

Restrict push CI to main, fix permissions

---

compiler_opt/es/blackbox_evaluator.py
compiler_opt/es/blackbox_learner.py
compiler_opt/es/blackbox_learner_test.py

This patch adjusts blackbox_learner so that it returns an entire policy rather than just the bytes of the policy. When actually running evaluations, we need to write out the full policy, including the output spec, to disk so the compiler can pick it up. Before this patch, we were not passing along the output spec to the worker.

Pass entire policy in blackbox_learner

---

compiler_opt/es/policy_utils_test.py

This patch adds a path prefix to all the uses of vocab within the policy utils test so that a path prefix can easily be added in downstream repository instances.

Add path prefix to policy utils test

---

compiler_opt/es/blackbox_learner_test.py
compiler_opt/es/blackbox_optimizers_test.py
compiler_opt/es/es_trainer.py
compiler_opt/es/es_trainer_lib.py

This patch fixes some import related style guide violations, particularly the importing of multiple modules/packages on a single line. Some internal tooling is not able to effectively analyze these patterns (given they don't show up often since they're banned by the style guide) which is relatively annoying.
We also should not be importing individual classes/functions, so fix those too when they coincide with the previous point.

Fix some import related style guide violations in ES

---

compiler_opt/es/blackbox_evaluator_test.py
compiler_opt/es/blackbox_learner_test.py
compiler_opt/es/blackbox_test_utils.py

This doesn't technically remove a circular dependency, but it does remove an awkward one.

Refactor test ESWorker to separate class

---

compiler_opt/rl/train_bc.py

This patch adds support for emitting hyperparameter information from the train_bc script into Tensorboard. This specifically focuses on values specified on the command line (i.e., ones that would vary during an experiment).

Add support for emitting hparam info from train_bc script

---

compiler_opt/es/blackbox_learner.py

This patch makes blackbox learner write percentiles of the reward along with the maximum reward to Tensorboard so that there is more exact information on the distribution of the reward per step rather than needing to resort to the distribution/histogram which do not have great support for analyzing numerically within tensorboard.

Add support for logging max/percentiles of reward to tensorboard in ES

---

compiler_opt/distributed/buffered_scheduler_test.py

This is necessary to enable the test to run internally and makes it consistent with other tests that call multiprocessing functionality under the hood.

Use multiprocessing.handle_test_main in buffered_scheduler_test

---

compiler_opt/rl/generate_bc_trajectories.py
compiler_opt/rl/generate_bc_trajectories_test.py

Initial ExplorationWorker commit. ExplorationWorker implements the
interactive clang compilation together with exploration for a
given module. This commit adds the class with its compile_module
function which will compile the module with a given compiler policy.

Initial ExplorationWorker commit

---

compiler_opt/rl/generate_bc_trajectories.py
compiler_opt/rl/generate_bc_trajectories_test.py

Explores the module using the given policy and the exploration distr.
This implementation assumes the action set is only {0,1} and will just
switch the action played at explore_step.

explore_function part of ExplorationWorker

---

compiler_opt/rl/generate_bc_trajectories.py
compiler_opt/rl/generate_bc_trajectories_test.py

Commit gen_trajectories() which is the function that loads the modules corpus, creates the worker manager to be used with ModuleWorker, collects the results and writes the results to file.

[BC] Generate trajectories

---

compiler_opt/tools/generate_default_trace.py

This patch removes an outdated comment (related to importing typing annotations and then leaving everything in strings to a lack of support from tooling at the time), removes a pylint disabled error as it no longer applies, and removes one no longer used type definition.

Fix some typing issue in generate_default_trace

---

compiler_opt/distributed/worker_test.py
compiler_opt/es/blackbox_learner_test.py
compiler_opt/rl/agent_config_test.py

If a test needs to `gin.bind_parameter` it should also clear that, or make the binding within a `gin.config_scope`, otherwise the bindings may leak to other tests if all the tests are run by e.g. pytest.
This patch uses both approaches: for tests that set up bindings in `setUp` we clear in `tearDown`, else we use the scoped approach.
Issue #394

Handle `gin.bind_parameter` in tests

---

.github/workflows/main.yml

Github will soon be moving ubuntu-latest to 24.04. This patch explicitly specifes 22.04 so that we can explicitly validate and upgrade rather than potentially having our CI break randomly.

Explicitly specify ubuntu version

---

Dockerfile

In preparation for deprecating support for python 3.8 and 3.9, bump the main docker container to python 3.10.

Change main docker container to python3.10

---

.github/workflows/main.yml

Now that all the users of mlcompileropt are containerized, we can drop support for Python 3.8 and 3.9.

Drop CI for Python 3.8 and 3.9

---

compiler_opt/es/es_trainer_lib.py

This patch makes es_trainer_lib load an actual corpus from the provided path rather than creating a dummy test corpus. Additionally, we also begin passing the replace_compilation_flags parameter, which is necessary for rewriting the paths to PGO profiles.

Use actual corpus in es_trainer_lib

---

.github/workflows/main.yml
compiler_opt/rl/distributed/agent.py
compiler_opt/rl/distributed/learner.py
compiler_opt/rl/regalloc/regalloc_network.py

Python 3.11 is the version used internally at Google, and testing a more recent version shouldn't hurt.

Add Python 3.11 to CI checks

---

compiler_opt/rl/imitation_learning/generate_bc_trajectories.py
compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py
compiler_opt/rl/imitation_learning/generate_bc_trajectories_test.py
compiler_opt/rl/inlining/env.py
compiler_opt/rl/inlining/gin_configs/imitation_learning.gin
compiler_opt/rl/inlining/imitation_learning_config.py
compiler_opt/rl/inlining/imitation_learning_runner.py

Adding configs for collecting imitation learning trajectories for inlining for size.

[BC] Inlining for size configs.

---

compiler_opt/rl/policy_saver_test.py
compiler_opt/testing/__init__.py
compiler_opt/testing/model_test_utils.py

This patch factors the _gen_test_model function in policy_saver_test
into a separate module in a new testing subdirectory to facilitate reuse
across tests. This is intended to be used in the regalloc_trace_worker
test which has to create a test model to test that everything works with
TFLite.

Refactor gen_test_model to separate module

---

.pylintrc

After upgrading pytype, it now writes a bunch of .pyi files into the .pytype directory. yapf and pylint pick these directories up and report a ton of issues that are completely meaningless. This patch makes it so that pylint ignores any files within .pytype. yapf does not have any option in the config to ignore files, so just blanket running yapf . -ir or specifying individual files is still necessary, but I think that should be less interruptive. This is purely a developer workflow improvement.

Ignore .pytype directory for pylint

---

compiler_opt/es/blackbox_evaluator.py
compiler_opt/es/blackbox_evaluator_test.py

Previously this function was implemented by subclasses. Move it to the
base class given everything we have planned so far
(TraceBlackboxEvaluator) will use the same implementation.

Move get_rewards to BlackboxEvaluator base class

---

compiler_opt/benchmark/benchmark_chromium.py
compiler_opt/benchmark/benchmark_report_test.py
compiler_opt/benchmark/filter_tests.py
compiler_opt/benchmark/gtest_executable_utils.py
compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/es/blackbox_learner.py
compiler_opt/es/regalloc_trace/regalloc_trace_worker.py
compiler_opt/rl/corpus.py
compiler_opt/rl/data_reader.py
compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py
compiler_opt/rl/imitation_learning/generate_bc_trajectories_test.py
compiler_opt/rl/imitation_learning/weighted_bc_trainer_lib.py
compiler_opt/rl/inlining/config.py
compiler_opt/rl/inlining/imitation_learning_config.py
compiler_opt/rl/log_reader.py
compiler_opt/rl/policy_saver.py
compiler_opt/rl/regalloc/config.py
compiler_opt/rl/regalloc_priority/config.py
compiler_opt/testing/model_test_utils.py
compiler_opt/tools/feature_importance.py
compiler_opt/tools/feature_importance_utils.py
compiler_opt/tools/generate_vocab.py

```
% ruff check --select=ASYNC,C4,E,F,PERF,PIE,W \
--ignore=E722,E731,E741,F401,PERF203,PIE790 \
--line-length=130 \
--statistics
11	C402   	[*] unnecessary-generator-dict
11	W293   	[*] blank-line-with-whitespace
8	PERF401	[ ] manual-list-comprehension
5	C401   	[*] unnecessary-generator-set
2	C405   	[*] unnecessary-literal-set
2	PIE808 	[*] unnecessary-range-start
1	C413   	[*] unnecessary-call-around-sorted
1	PERF102	[*] incorrect-dict-iterator
[*] fixable with `ruff check --fix`
```
% [`ruff rule PERF401`](https://docs.astral.sh/ruff/rules/manual-list-comprehension/)
Derived from the **Perflint** linter.
Fix is sometimes available.
Checks for `for` loops that can be replaced by a list comprehension.
When creating a transformed list from an existing list using a for-loop,
prefer a …

ruff rules for comprehensions and performance

---

compiler_opt/distributed/worker.py
compiler_opt/rl/data_collector_test.py
compiler_opt/rl/imitation_learning/weighted_bc_trainer_lib.py
compiler_opt/rl/local_data_collector_test.py
pyproject.toml

% [`ruff rule YTT204`](https://docs.astral.sh/ruff/rules/sys-version-info-minor-cmp-int) `sys-version-info-minor-cmp-int`
% [`ruff rule E741`](https://docs.astral.sh/ruff/rules/ambiguous-variable-name)
Derived from the **pycodestyle** linter.
Checks for the use of the characters 'l', 'O', or 'I' as variable names.
Note: This rule is automatically disabled for all stub files
(files with `.pyi` extensions). The rule has little relevance for authors
of stubs: a well-written stub should aim to faithfully represent the
interface of the equivalent .py file as it exists at runtime, including any
ambiguously named variables in the runtime module.
In some fonts, these characters are indistinguishable from the
numerals one and zero. When tempted to use 'l', use 'L' instead.
```python
l = 0
O = 123 …
```

misc: ruff rules E741 and YTT204

---

compiler_opt/es/es_trainer_lib.py

This is already configurable through gin in policy_utils, is not consistently
used within es_trainer_lib, and overall just adds unnecessary complexity.

Remove greedy flag from es_trainer_lib

---

compiler_opt/rl/env_test.py
compiler_opt/rl/log_reader.py
compiler_opt/rl/log_reader_test.py

The log format has a few places where we insert `\n` for human readability. They should be checked they are indeed just that character. This will allow us, in a subsequent PR, to avoid infinitely-blocking cases due to the process producing the log exiting unexpectedtly, by inserting errors into the reader to unblock and exit it.
Similarly, checking that the tensor data received matches in size what was expected.
Refactored a bit the test utility for constructing examples.

log_reader: tighten parsing

---

compiler_opt/distributed/local/local_worker_manager_test.py

When run in pytest, the test flag for `test_flag_parsing` isn't defined in the main module, so cloudpickle will serialize it by reference (good). That changes when we run the test from the command line, as `FlagValue` isn't serializable.

Fix local_worker_manager_test when run from command line

---

pyproject.toml

We make use of kwargs quite a bit, and it's sometimes necessary to pass then through, e.g. to workers from the worker manager. It looks (aesthetically, at least) cleaner to pass as `key=value` rather than `"key":value`, also, we can avoid silly typos like `"k ey"`.

Ignore ruff C408

---

compiler_opt/distributed/buffered_scheduler_test.py
compiler_opt/distributed/local/local_worker_manager_test.py
compiler_opt/es/blackbox_learner_test.py

We used cloudpickle to make it easy to author tests where the
test worker is defined in the test function. The problem is that
cloudpickle will also try to serialize by value classes defined in the
`__main__` module, which leads to serialization problems when e.g. the worker class
references in its members unpickleable things.
Also, revert #452 as it is addressed by this change.

Use standard pickle, and make pickler an option

---

compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py
compiler_opt/tools/generate_vocab.py
pyproject.toml

This patch switches from using the default numpy RNG to explicitly using a specific RNG. This is reccomended by numpy and identified by Ruff's NPY002 rule. This keeps things out of global state which makes reasoning about RNG a bit easier, although the code is a bit more verbose.
Fixes #460.

Do not use global Numpy RNG

---

compiler_opt/es/blackbox_evaluator.py
compiler_opt/es/blackbox_evaluator_test.py
compiler_opt/es/blackbox_learner.py
compiler_opt/es/es_trainer_lib.py

This patch makes the trace blackbox evaluator return a relative reward rather
than the raw reward. This makes the rewards actually meaningful, and also
prevents overflowing calculatings in blackbox_optimizer which previously
made the new model weights NaN.

Compute relative reward in trace blackbox evaluator

---

compiler_opt/distributed/local/local_worker_manager.py
compiler_opt/distributed/worker_manager.py
compiler_opt/es/es_trainer_lib.py
compiler_opt/rl/distributed/ppo_collect_lib.py
compiler_opt/rl/distributed/ppo_eval_lib.py
compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py
compiler_opt/rl/train_locally.py
compiler_opt/tools/generate_default_trace.py

This patch introduces a base class that worker pool managers can inherit from. This enforces the interface, particularly for instantiation, that we have been having a bit of trouble with recently given some recent refactorings. I've validated that this patch would have caught the issues that have already been fixed.

Add base class for WorkerPoolManagers

---

compiler_opt/es/es_trainer_lib.py

This patch adds a num_workers flag to es_trainer. This better matches the behavior of the train_locally script, which is important for some internal scripts for distributed training. Choosing the number of workers based on the number of perturbations also does not take into consideration the underlying hardware at all, which should be what determines the worker count. The current logic already did not take into account antithetic sampling doubling the number of models to evaluate per iteration.

Add num_workers flag to es_trainer

---

compiler_opt/es/regalloc_trace/regalloc_trace_worker.py
compiler_opt/es/regalloc_trace/regalloc_trace_worker_test.py

This patch adds a new argument to regalloc_trace_worker that can be set in a gin file for appending additional arguments to basic_block_trace_model.

Add argument to append options to modelling invocations

---

compiler_opt/es/blackbox_learner.py
compiler_opt/es/blackbox_learner_test.py

This patch adds a config option to BlackboxLearnerConfig that enables saving the best model when a new best comes up. This patch also adds in support in BlackboxLearner to actually save the model to the save directory.

Add option to save best model in ES

---

compiler_opt/tools/generate_default_trace.py
compiler_opt/tools/generate_default_trace_test.py

This patch adds an option to generate_default_trace to output the keys associated with the examples. This is primarily intended for use in extracting functions that contain eviction decisions to improve the efficiency of the new training workflow for ES regalloc trace modelling. However, this might also be useful in other circumstances if more introspection into the data is needed.

Add option to generate_default_trace to output keys

---

compiler_opt/es/blackbox_learner.py

Before this patch, the scalar name would end up as containing the value of the percentile rather than the percentile that we are trying to compute. We then end up with a bunch of one point metrics which clutters the UI and also means we cannot get any information about the actual percentiles. This patch fixes that by actually naming the scalar after the percentile that we are trying to compute.

Name scalar based on percentile to report

---

compiler_opt/es/blackbox_learner_test.py

This patch adds a unit test to blackbox_learner for testing that we correctly save the best model, or at least that it does get saved.

Add test for saving the best model

---

compiler_opt/es/blackbox_evaluator_test.py
compiler_opt/es/blackbox_learner.py
compiler_opt/es/blackbox_learner_test.py
compiler_opt/es/blackbox_test_utils.py

The variable name was bad and it wasn't caught by static analysis as we were setting a new variable before actually using it. This caused the best model each iteration to get saved whether or not it was actually better than all previous models.

Fix saving best policy in ES

---

compiler_opt/es/blackbox_learner_test.py

The two new tests introduced around saving the best model would be flaky depending upon how work got scheduled on the worker pool. This was particularly apparent on the github actions workers where apparently there are not enough cores to make things work properly. This patch fixes that issue by only setting up a single worker, ensuring that there are is only one way to schedule the work.

Fix flaky tests in blackbox_learner_test

---

compiler_opt/es/blackbox_evaluator_test.py
compiler_opt/es/blackbox_learner_test.py
compiler_opt/es/blackbox_test_utils.py

This patch cleans up parameteres for the test ES workers. Previously they would accept things like an argument and a set of keyword arguments that were never used. Drop these as they are completely unnecessary and make things a bit more cluttered.

Cleanup parameters for test ES workers

---

buildbot/build_tflite.sh

The upstream patch (https://github.com/intel/ARM_NEON_2_x86_SSE/pull/80) landed, so we should be using that rather than manually patching the CMake file.

Bump NEON_2_SSE_TAG

---

compiler_opt/tools/regalloc_trace/__init__.py
compiler_opt/tools/regalloc_trace/compile_corpus.py

This patch adds a script that enables compiling a corpus with the
regalloc trace worker. This is intended for use when partially compiling
a corpus and enables extracting out only the functions that matter for
register allocation decisions.
This is intended to be used before training begins to run all the middle
end optimizations. This then allows for functions to be extracted after
all IPO has taken place so we can then compile them all separately
by just running the backend. This script also supports compiling all the
way to asm to enable testing with basic_block_trace_model.
This script is typically used with --mode=full so that basic blocks in
the trace that are in functions that do not have regalloc decisions can
get serialized. The script is then run again with --mode=bc to run all …

Add a script to compile a corpus

---

compiler_opt/rl/corpus.py
compiler_opt/tools/regalloc_trace/extract_functions.py

This patch makes RegallocTraceWorker.build_corpus public rather than
internal. It is being used in places outside of the class itself so
should have a well defined public API. This patch fixes that, adds
docstrings, and updates users.

Make RegallocTraceWorker.build_corpus public

---

compiler_opt/rl/trainer.py
compiler_opt/rl/trainer_test.py

This patch adds hooks to the train process. This enables adding
functions that can run every n steps, like a function that evaluates the
model and writes the results out to tensorboard for later evaluation.

Add hooks in the trainer

---

compiler_opt/rl/train_bc.py

This patch moves where we save hparams from the end of the train_bc script to before we start training. This means that we can use the tensorboard hparams dashboard at the beginning of experiments and as things progress rather than only at the end when all experiments have concluded.

Save hparams at the beginning of train_bc

---

compiler_opt/es/blackbox_learner_test.py

blackbox_learner_test was using the tempdir (ie /tmp) rather than
absltest managed temp directories that are cleaned up at the end of the
test. This patch fixes it so that we are using the proper temp
directories.
Without this patch some failures for patches up the stack were not
emerging due to files that were leftover in /tmp.

Use unittest framework tempdirs in blackbox_learner_test

---

compiler_opt/es/blackbox_evaluator.py
compiler_opt/es/blackbox_evaluator_test.py

This patch makes TraceBlackboxEvaluator support batched bb traces.
Essentially this means we can split all of the bb traces obtained from a
single memtrace into a bunch of chunks. We can then evaluate only one of
these chunks per perturbation. This adds some randomness to the training
which can be good and also massively speeds up evaluation.

Support batched bb traces in TraceBlackboxEvaluator

---

compiler_opt/rl/train_locally.py
compiler_opt/rl/train_locally_lib.py

We have additional binaries that call into train_eval to take advantage of internal infrastructure. The recent flag refactoring change causes issues as if we wanted train_eval we previously had to import the binary which already defined the flags. This patch makes the structure a lot cleaner.

Split train_locally into a binary and a library

---

compiler_opt/tools/regalloc_trace/compile_corpus.py

This makes it so that we do not have to remember to add it when running training by making it correct at the time of construction. This would have prevented me from spawning a bunch of training jobs while forgetting the flag.

Add -disable-llvm-passes in compile_corpus.py

---

compiler_opt/es/blackbox_learner_test.py
compiler_opt/es/blackbox_test_utils.py

Some of the tests around the "save best model" functionality were
changed up in 6cf15b30ea80282a7a74e7c07092af2887cc1a86 as it touched
SamplingBlackboxEvaluator which is used in the tests in a way that made
them not work. This patch restores the functionality by changing up how
the tests work a bit so they test what they are intended to.

Restore best model test functionality

---

buildbot/buildbot_init.sh

We are currently running into what looks like some compilation timeouts in AMDGPU table generated code. These issues are inherenet to what seems like the g++ version on debian 12. We probably want to be using a LLVM based toolchain anyways.

[Buildbot] Update toolchain to clang/lld 20

---

buildbot/build_tflite.sh

Some of our servers default installation to `lib64` instead of `lib`. This patch asks CMakeCache which one did it use.

[buildbot] Adjust gemmlowp_INSTALL_LIBDIR based on CMake's choices
