.gitignore, compiler_opt/tools/generate_default_trace.py
Regression introduced in 09b41a8 (missing delete flags)
Also added .idea (Pycharm configs) to .gitignore
=> Fix generate_default_trace

compiler_opt/tools/generate_default_trace.py
Regression introduced in 32a5c1c
Runners became un-pickle-able due to Runners now containing a WorkerCancellationManager which contained a threading.Lock()
=> Fix generate_default_trace.py

compiler_opt/tools/extract_ir_test.py, compiler_opt/tools/generate_default_trace.py, compiler_opt/tools/generate_default_trace_test.py, pytest.ini
avoid generate_default_trace breaking due to api changes
=> test for generate_default_trace

compiler_opt/distributed/local/local_worker_manager.py
- Prevents attempting to spawn num_workers * min(32, cores) number of clangs (python errors out)
- max_worker count is adjustable via `pool_threads` parameter in LocalWorkerPool constructor
=> Set max workers for LocalWorkerManager

compiler_opt/distributed/local/local_worker_manager.py
=> LocalWorker: Fix nr threads to 1

buildbot/build_tflite.sh, buildbot/buildbot_init.sh
Also bumping Ruy hash to capture last build-related fix
=> Enable building tflite on 'dev*'  buildbots

README.md, docs/contributing.md
Small edits to contributions page and adding a link to contributions page on main README.
=> Update to Contributions

compiler_opt/distributed/local/local_worker_manager.py
- Add a get_context()
- Fix a signature
- Update module docstring
=> Tidy up local_worker_manager

compiler_opt/distributed/local/local_worker_manager.py
=> Add get_context() for cpu_count call

compiler_opt/tools/generate_default_trace_test.py
One line diff that should fix the formatting error currently breaking the CI.
=> Fix formatting for CI

compiler_opt/rl/compilation_runner.py
Currently, whenever a TF model gets loaded in by LLVM in the
development mode advisors, TF outputs a slew of info messages
to STDOUT that aren't particularly useful. This patch gets
rid of those messages by setting an environment variable when
running the compilation commands that only enables warnings
and errors to be printed to the console. This makes it much
easier to see progress/results in several of the scripts within
this repository such as train_locally.py and
generate_default_trace.py when grabbing performance data for a
policy.
=> Prevent TF from logging info messages during data collection

compiler_opt/distributed/local/buffered_scheduler.py, compiler_opt/distributed/local/buffered_scheduler_test.py, compiler_opt/distributed/local/local_worker_manager.py, compiler_opt/distributed/worker.py, compiler_opt/rl/local_data_collector.py, compiler_opt/rl/local_data_collector_test.py
- Adds a buffered load balancer, which by default maintains at least 2 tasks assigned to each worker.
Closes #91
=> Add load balancer

compiler_opt/tools/generate_test_model.py
a script for generating test model, can be used for:
1. want to have a model to test
2. have test for testing tflite saving (next step)
=> a script for generating test model.

compiler_opt/rl/corpus.py, compiler_opt/rl/corpus_test.py, compiler_opt/tools/generate_default_trace.py
less mutability, easier readability.
=> Corpus.filter returns a new Corpus

compiler_opt/rl/corpus_test.py
=> Use `assertIn` in `corpus_test.py`

compiler_opt/rl/regalloc_priority/__init__.py, compiler_opt/rl/regalloc_priority/config.py, compiler_opt/rl/regalloc_priority/gin_configs/common.gin, compiler_opt/rl/regalloc_priority/gin_configs/ppo_nn_agent.gin, compiler_opt/rl/regalloc_priority/regalloc_priority_runner.py
This PR introduce a config for priority prediction.
=> Priority Prediction Configs

.github/workflows/main.yml
=> fix(ci): replace set-output to GITHUB_OUTPUT

Dockerfile
This is necessary for running tools in this repository.
=> Set PYTHONPATH environment variable

compiler_opt/rl/log_reader.py, compiler_opt/rl/log_reader_test.py
This was introduced in https://reviews.llvm.org/D139370
=> Add support for the new logging mechanism in llvm

compiler_opt/rl/log_reader.py, compiler_opt/rl/log_reader_test.py
This is because we will need the name to construct `Trajectory`es, and, while we could fetch it from elsewhere (like from the header), it's just easier to have it attached to the object, and the cost is small. In particular, in lists of repeated `TensorValue`s, pickling ensures only one copy of an object is made.
=> Added `spec` back to TensorValue

compiler_opt/tools/generate_default_trace.py, compiler_opt/tools/generate_default_trace_test.py
* making `main` take care of gin bindings, and any additional parameters, so the worker pool type doesn't get overridden by `main`'s args
* making sure gin configuration for the underlying worker makes it through.
This also fixes the actual tool, since we weren't passing the gin config of the underlying task correctly.
(Depends on #223)
=> Make `generate_default_trace_test` closer to actual use

compiler_opt/rl/compilation_runner.py
Write a log message when compilation attempts fail or time out.
=> Log failed compilation attempts

compiler_opt/rl/compilation_runner.py, compiler_opt/rl/compilation_runner_test.py, compiler_opt/rl/inlining/inlining_runner.py, compiler_opt/rl/regalloc/regalloc_runner.py, compiler_opt/rl/regalloc_priority/regalloc_priority_runner.py
This allows users to manually re-run commands after the fact to investigate failures.
=> compilation_runner: Option to keep temporary files

compiler_opt/rl/agent_creators.py, compiler_opt/rl/agent_creators_test.py, compiler_opt/rl/data_reader.py, compiler_opt/rl/data_reader_test.py, compiler_opt/rl/distributed/ppo_collect_lib.py, compiler_opt/rl/distributed/ppo_eval_lib.py, compiler_opt/rl/distributed/ppo_train_lib.py, compiler_opt/rl/inlining/gin_configs/actor_behavioral_cloning_nn_agent.gin, compiler_opt/rl/inlining/gin_configs/behavioral_cloning_nn_agent.gin, compiler_opt/rl/inlining/gin_configs/behavioral_cloning_rnn_agent.gin, compiler_opt/rl/inlining/gin_configs/dqn_nn_agent.gin, compiler_opt/rl/inlining/gin_configs/dqn_rnn_agent.gin, compiler_opt/rl/inlining/gin_configs/ppo_nn_agent.gin, compiler_opt/rl/regalloc/gin_configs/behavioral_cloning_nn_agent.gin, compiler_opt/rl/regalloc/gin_configs/ppo_nn_agent.gin, compiler_opt/rl/regalloc_priority/gin_configs/ppo_nn_agent.gin, compiler_opt/rl/train_bc.py, compiler_opt/rl/train_locally.py, compiler_opt/tools/feature_importance.py, compiler_opt/tools/generate_test_model.py, compiler_opt/tools/generate_test_model_test.py
Replace agent ID and if-checks in various parts of the code (in agent creation and in data processing, respectivelly) with `AgentConfig`, an abstraction encapsulating the various behaviors.
=> Refactor agent configuration.

compiler_opt/tools/extract_ir_lib.py
Now that extract_ir_lib.py is being used in other projects through the Pip package rather than just the ml-compiler-opt CLI tooling, it would be good to have better documentation on how to use these functions. This commit adds in doc strings for some of the functions that are most likely to be used in downstream projects and fixes up some other docstrings.
This was motivated by not passing an empty string instead of None to cmd_filter which led to some annoying debugging when other issues were at play.
=> Add docstrings to extract_ir_lib.py

compiler_opt/tools/extract_ir_lib.py
This is a minor refactoring that simplifies the code base for future work. It doesn't make a lot of sense to keep this as a separate function and then use a functools.partial to setup the correct command line arguments when we can just do it explicitly using a subfunction.
=> Move extract_artifacts to inside run_extractions

buildbot/build_tflite.sh, buildbot/buildbot_init.sh
Reverts google/ml-compiler-opt#295
=> Revert "Reland "Bump TFLite commit (#293)""

compiler_opt/distributed/local/local_worker_manager.py
Makes it easier to work with local classes, like the ones produced by functions.
=> [local-worker-mgr] Use `cloudpickle`

compiler_opt/rl/generate_bc_trajectories.py, compiler_opt/rl/generate_bc_trajectories_test.py
Refactor field names to start with _ in ExplorationWithPolicy.
=> [NFC] refactor field names in ExplorationWithPolicy

compiler_opt/rl/generate_bc_trajectories.py, compiler_opt/rl/generate_bc_trajectories_test.py
ModuleWorker is responsible for distributing the ExplorationWorker workloads and post-processing the ExplorationWorker.explore_function results. ModuleWorkerUtility has the post-processing utilities used in ModuleWorker.
=> [BC] ModuleWorker and ModuleWorkerUtility

compiler_opt/rl/imitation_learning/__init__.py
=> Add init file to new imitation_learning directory

.pylintrc, Pipfile, Pipfile.lock, compiler_opt/distributed/buffered_scheduler_test.py, compiler_opt/distributed/worker_test.py, compiler_opt/es/blackbox_learner.py, compiler_opt/es/blackbox_optimizers.py, compiler_opt/rl/compilation_runner.py, compiler_opt/rl/local_data_collector.py, compiler_opt/type_map.py
This patch bumps pylint to the latest version. This is in preparation for bumping the rest of the deps.
=> Bump pylint

compiler_opt/benchmark/filter_tests.py, compiler_opt/es/blackbox_optimizers.py, compiler_opt/rl/compilation_runner.py, compiler_opt/rl/distributed/agent.py, compiler_opt/rl/distributed/ppo_train_lib.py, compiler_opt/rl/env.py, compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py, compiler_opt/rl/imitation_learning/weighted_bc_trainer_lib.py, compiler_opt/rl/inlining/inlining_runner.py, compiler_opt/rl/policy_saver.py, compiler_opt/rl/random_net_distillation.py, compiler_opt/rl/regalloc/regalloc_runner.py, compiler_opt/tools/feature_importance_graphs.py, compiler_opt/tools/feature_importance_utils.py, docs/benchmarking.md, docs/inlining-demo/demo.md, docs/regalloc-demo/demo.md
https://github.com/codespell-project/codespell
% `pipx run codespell --skip="*.ipynb,*.json,*.lock" --write-change`
=> Fix typos discovered by codespell

compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py, compiler_opt/rl/inlining/env.py, compiler_opt/rl/inlining/gin_configs/imitation_learning.gin, compiler_opt/rl/inlining/imitation_learning_config.py
Update common.gin and immitation_learning.gin. Further, ensure the ModuleWorker and InliningForSizeTask use the same key.
=> [BC] Update configs

compiler_opt/rl/imitation_learning/weighted_bc_trainer_lib.py, compiler_opt/rl/inlining/imitation_learning_config.py, compiler_opt/rl/inlining/imitation_learning_runner.py
Fixed ```metric.reset_states() -> metric.reset_state()```, removed a
debugging line in ```weighted_bc_trainer_lib```, slight naming changes
for ```generate_bc_trajectories```.
=> [BC] ```weighted_bc_trainer_lib.py``` bug fixes

compiler_opt/distributed/local/local_worker_manager.py, compiler_opt/distributed/local/local_worker_manager_test.py
Without this patch, command line-passed flags like compilation timeout would be dropped.
There's no apparent reason we wouldn't want to always pass this, but in case we do, the code is organized to enable making that easily opt-able in.
=> [local worker] Parse `sys.argv` in child processes

compiler_opt/distributed/local/local_worker_manager.py
They were made "internal" unnecessarily (by the convention of the `_` prefix) in PR #453
=> Make public (again) the create and close APIs in local_worker_manager

compiler_opt/rl/imitation_learning/generate_bc_trajectories_lib.py, compiler_opt/rl/imitation_learning/generate_bc_trajectories_test.py
- np.Inf becomes np.inf
- explicit `module` for a test gin-configurable
=> Fixes for downstream integration:

compiler_opt/rl/imitation_learning/generate_bc_trajectories_test.py, compiler_opt/tools/regalloc_trace/group_functions.py
This look leftover from debugging. Remove them given they aren't doing
anything.
=> Remove leftover comments in generate_bc_trajectories_test

compiler_opt/es/blackbox_evaluator_test.py
I broke a test that I forgot to run locally and then eagerly ran spr land instead of actually checking the CI results.
=> Fix CI post b1aa19a694a6a53ef3541e9b0841d3a716fe3df3
